global:
  smtp_from: 'no-reply@example.com'
  smtp_smarthost: 'host.docker.internal:25' 
  smtp_require_tls: false

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
 group_by: ['alertname']
 group_wait: 3s
 group_interval: 5s
 repeat_interval: 5s
 receiver: mail-receiver

receivers:
- name: 'mail-receiver'
  email_configs:
  - to: 'admins@example.com'
    send_resolved: true
